# TCL File Generated by Component Editor 22.1
# Sun Jan 11 10:42:03 MSK 2026
# DO NOT MODIFY


# 
# DATA_Gen "DATA_Gen" v1.0
#  2026.01.11.10:42:03
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DATA_Gen
# 
set_module_property DESCRIPTION ""
set_module_property NAME DATA_Gen
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DATA_Gen
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DATA_Gen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DATA_Gen.v VERILOG PATH ./src/DATA_Gen.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL DATA_Gen
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DATA_Gen.v VERILOG PATH ./src/DATA_Gen.v


# 
# parameters
# 
add_parameter PACKET_WORD_LEN_BITS INTEGER 8 ""
set_parameter_property PACKET_WORD_LEN_BITS DEFAULT_VALUE 8
set_parameter_property PACKET_WORD_LEN_BITS DISPLAY_NAME PACKET_WORD_LEN_BITS
set_parameter_property PACKET_WORD_LEN_BITS WIDTH ""
set_parameter_property PACKET_WORD_LEN_BITS TYPE INTEGER
set_parameter_property PACKET_WORD_LEN_BITS UNITS None
set_parameter_property PACKET_WORD_LEN_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PACKET_WORD_LEN_BITS DESCRIPTION ""
set_parameter_property PACKET_WORD_LEN_BITS HDL_PARAMETER true
add_parameter PACKET_LEN_WORDS INTEGER 8
set_parameter_property PACKET_LEN_WORDS DEFAULT_VALUE 8
set_parameter_property PACKET_LEN_WORDS DISPLAY_NAME PACKET_LEN_WORDS
set_parameter_property PACKET_LEN_WORDS TYPE INTEGER
set_parameter_property PACKET_LEN_WORDS UNITS None
set_parameter_property PACKET_LEN_WORDS HDL_PARAMETER true
add_parameter PACKET_ID STD_LOGIC_VECTOR 174
set_parameter_property PACKET_ID DEFAULT_VALUE 174
set_parameter_property PACKET_ID DISPLAY_NAME PACKET_ID
set_parameter_property PACKET_ID WIDTH 9
set_parameter_property PACKET_ID TYPE STD_LOGIC_VECTOR
set_parameter_property PACKET_ID UNITS None
set_parameter_property PACKET_ID ALLOWED_RANGES 0:511
set_parameter_property PACKET_ID HDL_PARAMETER true
add_parameter PACKET_PAUSE_TICKS INTEGER 100
set_parameter_property PACKET_PAUSE_TICKS DEFAULT_VALUE 100
set_parameter_property PACKET_PAUSE_TICKS DISPLAY_NAME PACKET_PAUSE_TICKS
set_parameter_property PACKET_PAUSE_TICKS TYPE INTEGER
set_parameter_property PACKET_PAUSE_TICKS UNITS None
set_parameter_property PACKET_PAUSE_TICKS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point gen_en
# 
add_interface gen_en conduit end
set_interface_property gen_en associatedClock clock
set_interface_property gen_en associatedReset ""
set_interface_property gen_en ENABLED true
set_interface_property gen_en EXPORT_OF ""
set_interface_property gen_en PORT_NAME_MAP ""
set_interface_property gen_en CMSIS_SVD_VARIABLES ""
set_interface_property gen_en SVD_ADDRESS_GROUP ""

add_interface_port gen_en gen_en gen_en Input 1


# 
# connection point rstn
# 
add_interface rstn reset end
set_interface_property rstn associatedClock clock
set_interface_property rstn synchronousEdges DEASSERT
set_interface_property rstn ENABLED true
set_interface_property rstn EXPORT_OF ""
set_interface_property rstn PORT_NAME_MAP ""
set_interface_property rstn CMSIS_SVD_VARIABLES ""
set_interface_property rstn SVD_ADDRESS_GROUP ""

add_interface_port rstn rstn reset_n Input 1


# 
# connection point m_axis
# 
add_interface m_axis axi4stream start
set_interface_property m_axis associatedClock clock
set_interface_property m_axis associatedReset rstn
set_interface_property m_axis ENABLED true
set_interface_property m_axis EXPORT_OF ""
set_interface_property m_axis PORT_NAME_MAP ""
set_interface_property m_axis CMSIS_SVD_VARIABLES ""
set_interface_property m_axis SVD_ADDRESS_GROUP ""

add_interface_port m_axis m_axis_tdata tdata Output 8
add_interface_port m_axis m_axis_tlast tlast Output 1
add_interface_port m_axis m_axis_tready tready Input 1
add_interface_port m_axis m_axis_tvalid tvalid Output 1

