# TCL File Generated by Component Editor 22.1
# Sun Jan 11 15:34:37 MSK 2026
# DO NOT MODIFY


# 
# DATA_Checker "DATA_Checker" v1.0
#  2026.01.11.15:34:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module DATA_Checker
# 
set_module_property DESCRIPTION ""
set_module_property NAME DATA_Checker
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DATA_Checker
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DATA_Checker
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DATA_Checker.v VERILOG PATH ./src/DATA_Checker.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL DATA_Checker
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DATA_Checker.v VERILOG PATH ./src/DATA_Checker.v


# 
# parameters
# 
add_parameter PACKET_WORD_LEN_BITS INTEGER 8
set_parameter_property PACKET_WORD_LEN_BITS DEFAULT_VALUE 8
set_parameter_property PACKET_WORD_LEN_BITS DISPLAY_NAME PACKET_WORD_LEN_BITS
set_parameter_property PACKET_WORD_LEN_BITS TYPE INTEGER
set_parameter_property PACKET_WORD_LEN_BITS UNITS None
set_parameter_property PACKET_WORD_LEN_BITS HDL_PARAMETER true
add_parameter PACKET_LEN_WORDS INTEGER 8
set_parameter_property PACKET_LEN_WORDS DEFAULT_VALUE 8
set_parameter_property PACKET_LEN_WORDS DISPLAY_NAME PACKET_LEN_WORDS
set_parameter_property PACKET_LEN_WORDS TYPE INTEGER
set_parameter_property PACKET_LEN_WORDS UNITS None
set_parameter_property PACKET_LEN_WORDS HDL_PARAMETER true
add_parameter PACKET_ID STD_LOGIC_VECTOR 174
set_parameter_property PACKET_ID DEFAULT_VALUE 174
set_parameter_property PACKET_ID DISPLAY_NAME PACKET_ID
set_parameter_property PACKET_ID WIDTH 9
set_parameter_property PACKET_ID TYPE STD_LOGIC_VECTOR
set_parameter_property PACKET_ID UNITS None
set_parameter_property PACKET_ID ALLOWED_RANGES 0:511
set_parameter_property PACKET_ID HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point CS_ERR_CNT
# 
add_interface CS_ERR_CNT conduit end
set_interface_property CS_ERR_CNT associatedClock clock
set_interface_property CS_ERR_CNT associatedReset rstn
set_interface_property CS_ERR_CNT ENABLED true
set_interface_property CS_ERR_CNT EXPORT_OF ""
set_interface_property CS_ERR_CNT PORT_NAME_MAP ""
set_interface_property CS_ERR_CNT CMSIS_SVD_VARIABLES ""
set_interface_property CS_ERR_CNT SVD_ADDRESS_GROUP ""

add_interface_port CS_ERR_CNT CS_ERR_CNT cs_err_cnt Output 32


# 
# connection point rstn
# 
add_interface rstn reset end
set_interface_property rstn associatedClock clock
set_interface_property rstn synchronousEdges DEASSERT
set_interface_property rstn ENABLED true
set_interface_property rstn EXPORT_OF ""
set_interface_property rstn PORT_NAME_MAP ""
set_interface_property rstn CMSIS_SVD_VARIABLES ""
set_interface_property rstn SVD_ADDRESS_GROUP ""

add_interface_port rstn rstn reset_n Input 1


# 
# connection point DATA_ERR_CNT
# 
add_interface DATA_ERR_CNT conduit end
set_interface_property DATA_ERR_CNT associatedClock clock
set_interface_property DATA_ERR_CNT associatedReset rstn
set_interface_property DATA_ERR_CNT ENABLED true
set_interface_property DATA_ERR_CNT EXPORT_OF ""
set_interface_property DATA_ERR_CNT PORT_NAME_MAP ""
set_interface_property DATA_ERR_CNT CMSIS_SVD_VARIABLES ""
set_interface_property DATA_ERR_CNT SVD_ADDRESS_GROUP ""

add_interface_port DATA_ERR_CNT DATA_ERR_CNT data_err_cnt Output 32


# 
# connection point ID_ERR_CNT
# 
add_interface ID_ERR_CNT conduit end
set_interface_property ID_ERR_CNT associatedClock clock
set_interface_property ID_ERR_CNT associatedReset rstn
set_interface_property ID_ERR_CNT ENABLED true
set_interface_property ID_ERR_CNT EXPORT_OF ""
set_interface_property ID_ERR_CNT PORT_NAME_MAP ""
set_interface_property ID_ERR_CNT CMSIS_SVD_VARIABLES ""
set_interface_property ID_ERR_CNT SVD_ADDRESS_GROUP ""

add_interface_port ID_ERR_CNT ID_ERR_CNT id_err_cnt Output 32


# 
# connection point PKT_CNT
# 
add_interface PKT_CNT conduit end
set_interface_property PKT_CNT associatedClock clock
set_interface_property PKT_CNT associatedReset rstn
set_interface_property PKT_CNT ENABLED true
set_interface_property PKT_CNT EXPORT_OF ""
set_interface_property PKT_CNT PORT_NAME_MAP ""
set_interface_property PKT_CNT CMSIS_SVD_VARIABLES ""
set_interface_property PKT_CNT SVD_ADDRESS_GROUP ""

add_interface_port PKT_CNT PKT_CNT pkt_cnt Output 32


# 
# connection point s_axis
# 
add_interface s_axis axi4stream end
set_interface_property s_axis associatedClock clock
set_interface_property s_axis associatedReset rstn
set_interface_property s_axis ENABLED true
set_interface_property s_axis EXPORT_OF ""
set_interface_property s_axis PORT_NAME_MAP ""
set_interface_property s_axis CMSIS_SVD_VARIABLES ""
set_interface_property s_axis SVD_ADDRESS_GROUP ""

add_interface_port s_axis s_axis_tdata tdata Input "((PACKET_WORD_LEN_BITS-1)) - (0) + 1"
add_interface_port s_axis s_axis_tvalid tvalid Input 1
add_interface_port s_axis s_axis_tlast tlast Input 1
add_interface_port s_axis s_axis_tready tready Output 1

